# fly.toml app configuration file generated for weathered-frost-3224 on 2023-09-20T15:57:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-frost-3224"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
